### ISSUE TITLE
Please show more dates

### ISSUE THREAD

**Issue by WyseNynja** [rust-lang/rustup-components-history#1]
Clippy and and rls and some others are currently missing from every build shown. I would like to use the latest build that has both these components, but now I'm not sure what that is.

It would be helpful to be able to view the older generated pages.

Maybe the last column could be changed to show the most recent build where the component is present?

**Comment by mexus** [comment]
Hi @WyseNynja !
I guess we could simply increase the amount of dates that we analyse, but.. we need a help of a web-designer to make it look okay :)) I've just tried to make the table wider and it became a total mess on my screen.

In the ideal world we would store the data in a database or something, hence providing the information forever, not just for the last X days, but I was too lazy to introduce such a complicated mechanism (compared to how the things are done right now). PRs are welcome though! xD

I guess we could go a bit further into the past to figure out the latest availability dates for all the components on all the targets, but there are a certain points that make me feel uncomfortable:

* How many days should we look in the past? Given that the "service" is stateless and it re-generates all the pages on every run.
* If we look up for, let's say, for 20 days into the past, but render only the first 7 or 8 days, isn't it a waste?.. But this one is not a really strong point. I guess we can afford to download a couple of dozens of TOMLs on travis once a day :)

So currently the most promising option which could be implemented in the blink of an eye seems to be to fetch the availability data for X days (let's say 14 days for starters), render last 7 days and convert the last column into "last date available", what do you think of it?

**Comment by pietroalbini** [comment]
By the way, from an infra point of view, even 5x Travis build times are perfectly fine.

**Comment by mexus** [comment]
![image](https://user-images.githubusercontent.com/3609357/55669431-eeae4500-587f-11e9-8ddf-846e1c2c6a20.png)
Does it look okay?

**Comment by kennytm** [comment]
I think the "last available" column not being green is better.

**Comment by mexus** [comment]
@kennytm soryy I'm terrible at web design, could you pls pick the colours for me? :)
Currently I'm only using classes from the following list https://getbootstrap.com/docs/4.1/content/tables/#contextual-classes , but I guess it's not a big deal if we insert some custom colours.

Here's a raw file if you'd like to experiment on a real example: https://gist.github.com/mexus/ed9e4088fb7a6552568a2e3e31aac2e9

Thanks! :)

**Comment by kennytm** [comment]
@mexus I mean the column could just be colorless, so it won't appear mixed with the present/missing table.

**Comment by mexus** [comment]
Like that?
![image](https://user-images.githubusercontent.com/3609357/55670576-e3aee100-588e-11e9-8717-cff73687d07f.png)

**Comment by mexus** [comment]
Actually not too bad, let's wait a bit if anybody else has something to say on the matter

**Comment by mexus** [comment]
Hi @WyseNynja , could you please provide some feedback on a PR I've just pushed? Do you think it will fill the gap? Thanks ^_^

**Comment by WyseNynja** [comment]
This looks great to me. This definitely solves my problem. Thank you @mexus!

**Comment by mexus** [comment]
Great! There's still a room for improvement, like providing a way to find a date when a set of components is available (like `rls` and `clippy` at the same time), but let's go with PR #3 for now.
