### ISSUE TITLE
no successful build version for 'lldb-preview'

### ISSUE THREAD

**Issue by m-hugo** [rust-lang/rustup-components-history#12]
~/Downloads/servo-master$ cargo build --release
info: syncing channel updates for 'nightly-2019-09-28-x86_64-unknown-linux-gnu'
info: latest update on 2019-09-28, rust version 1.40.0-nightly (084beb83e 2019-09-27)
error: some components unavailable for download for channel nightly-2019-09-28: 'lldb-preview', 'miri'                                                             
If you require these components, please install and use the latest successful build version,                                                                                  
which you can find at <https://rust-lang.github.io/rustup-components-history>.

no successful build version at https://rust-lang.github.io/rustup-components-history
lldb-preview | missing | missing | missing | missing | missing | missing | missing | N/A

no file at http://rust-lang.github.io/rustup-components-history/last-available/x86_64-unknown-linux-gnu/lldb-preview

**Comment by mexus** [comment]
Well, it seems like the component was never available on that target. Any how, the tool is monitoring only the latest 22 days (it might be increased if required though).

**Comment by igrep** [comment]
To avoid the error you can ignore such a missing component by the `--force` option of `rustup toolchain install`.
E.g. `rustup toolchain install --force nightly`.

**Comment by mexus** [comment]
Closing the issue since it definitely doesn't relate to the component history tool. Please feel free to re-open the issue if you think otherwise!
