### ISSUE TITLE
rust-docs always missing on tier2 arm7 platform

### ISSUE THREAD

**Issue by progman1** [rust-lang/rustup-components-history#14]
hi

I develop on a raspberry pi (armv7-unknown-linux-gnueabihf)  which is tier2
and there are understandably missing components for it.
but why would rust-docs not be installable on this platform (or indeed any other )?
it is after all just a bunch of html files and therefore platform independent.

thanks.

**Comment by pietroalbini** [comment]
The documentation is not fully platform independent: there are some parts that are specific to a single OS/architecture/environment. We removed the documentation for tier 2 platforms as it was taking too much CI time to generate it.

**Comment by mexus** [comment]
Closing the issue since it definitely doesn't relate to the component history tool. Please feel free to re-open the issue if you think otherwise!
