### ISSUE TITLE
2020-04-17 still missing

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustup-components-history#15]
The latest nightly is not listed on https://rust-lang.github.io/rustup-components-history/ yet. Probably the recent Travis outage also messed up your cron job schedule (like it did with mine).

**Comment by RalfJung** [comment]
Looks like the cronjob currently runs around 13:30 -- more than half a day after the nightly is available.

This affects not just the website, but also CI that uses the "latest nightly with tool X" information.

**Comment by Mark-Simulacrum** [comment]
I think travis cronjobs run every 24 hours, so we'll need to kick it around 00:00 if we want to resync it. I can try to do so tonight if I don't forget -- but we should probably move to GHA which has native support for proper cronjobs that don't need this.

**Comment by RalfJung** [comment]
@pietroalbini once told me that nightlies take a bit to release, so 02:00 UTC is probably a better time. Hopefully someone in a US timezone can do that. ;)

Indeed Travis cron jobs are pretty bad...

**Comment by Mark-Simulacrum** [comment]
Yeah, should be around 9:30 PM my time I think (presuming I managed to get the timezones right). Shouldn't be a problem -- presuming I remember :)

**Comment by Mark-Simulacrum** [comment]
Alright, hopefully my button pushing has the right results. Going to close this for now, but we can reopen if needed.

**Comment by RalfJung** [comment]
Thanks, looking good. :)

**Comment by RalfJung** [comment]
@Mark-Simulacrum  Hm, something is off again... it's 8:00 UTC and https://rust-lang.github.io/rustup-components-history/ does not have today's nightly yet.

**Comment by RalfJung** [comment]
Oh actually the build ran at the right time but failed... will open a new issue.

**Comment by RalfJung** [comment]
Or rather not, looks spurious... @rust-lang/infra can someone retrigger https://travis-ci.com/github/rust-lang/rustup-components-history/builds/164852183 ?

**Comment by Mark-Simulacrum** [comment]
Retriggered.
