### ISSUE TITLE
No updates since 2020-05-09

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustup-components-history#17]
Something seems to have gone wrong, the latest nightly shown on the website is 2020-05-09.

**Comment by RalfJung** [comment]
They all look like timeouts, and nothing in the repo seems to have changed since the last working run. Very strange.

**Comment by Mark-Simulacrum** [comment]
AFAICT we just continuously increase the cache size on travis currently which is obviously not great. I've cleaned that out (we were at ~3 GB) and that seems to have fixed things for now -- we're now down to 629.52 MB.
