### ISSUE TITLE
Site did not update for 3 days

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustup-components-history#2]
The last update of https://rust-lang.github.io/rustup-components-history/ was at "03 Apr 2019, 02:16:17 UTC", that's more than 3 days ago.

**Comment by mexus** [comment]
hi @RalfJung , thanks for your finding!

**Comment by mexus** [comment]
@pietroalbini , it seems to be a problem with Travis, something related to a "migration", at list the project's page on travis says "This project hasn’t been migrated". Do you happen to know what that could be related to?
I have manually triggered the build for now, but it seems like we need to do something with a cron job..

**Comment by mexus** [comment]
It seems like @pietroalbini has silently fixed everything ;) Thanks, Pietro!

**Comment by pietroalbini** [comment]
Forgot to post here :sweat_smile:  
Thanks for reporting this issue!
