### ISSUE TITLE
Missing information in the website about latest nightly release

### ISSUE THREAD

**Issue by gabrielcbenedito** [rust-lang/rustup-components-history#20]
I think there may be some missing information on the website about the nightly release from 2020-09-01, but I may have misunderstand the information. I do get that this release is from yesterday and so I don't want to be rude here and "demand" an website update that fast. And I apologize if anyone feel offended.

As a side note, I would be grateful if some kind soul could teach me how to find out the missing components for a specific release. By learning that, I may be able to contribute for the website as well :blush: 

Environment:

```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
```shell
$ uname -a
Linux my_machine 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
```shell
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/gabriel/.rustup

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.48.0-nightly (130359cb0 2020-09-01)
```

**Comment by Mark-Simulacrum** [comment]
I'm pretty sure this is because the nightly was unusually released late (roughly 3 hours or so). Probably will be fixed tomorrow.

**Comment by mexus** [comment]
I guess we can close the issue since it was clearly an intermittent "issue", at least the problem has not appeared within almost 4 months :)
