### ISSUE TITLE
No update since 2021-05-11

### ISSUE THREAD

**Issue by wongsyrone** [rust-lang/rustup-components-history#34]
`Generated at 11 May 2021, 04:56:54 UTC` from https://rust-lang.github.io/rustup-components-history/, it seems it's broken.

**Comment by Manishearth** [comment]
cc @rust-lang/infra

**Comment by Mark-Simulacrum** [comment]
I think we had built up too large a cache; after purging that it seems to work.

**Comment by wongsyrone** [comment]
The same issue again. `Generated at 09 Jun 2021, 04:56:11 UTC`
@Mark-Simulacrum
cc @rust-lang/infra

**Comment by sagudev** [comment]
I am not sure, but travis is failing with `Could not authorize build request` which according to [this](https://stackoverflow.com/questions/41034694/travis-could-not-authorize-build-request/41078031) mean that @rust-lang/infra run out of free credit.

**Comment by Fuuzetsu** [comment]
> The same issue again. `Generated at 09 Jun 2021, 04:56:11 UTC`
> @Mark-Simulacrum
> cc @rust-lang/infra

I generated x86 for last few days locally, just in case someone stumbles upon here. Obviously will be out of date very quickly.

![f](https://user-images.githubusercontent.com/893115/122842671-c9129680-d338-11eb-8467-fa0928322210.png)
