### ISSUE TITLE
Website has not been updates in weeks

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustup-components-history#37]
https://rust-lang.github.io/rustup-components-history/ currently shows packet availability for 2021-06-09 and a few days before that. It looks like it hasn't been updated in almost a month. Did some cron job break (and no monitoring notice that)?

One side-effect of this is that all projects using Miri on CI will use the Miri from 2021-06-09 as the website says that's the latest nightly with a Miri.

Cc @rust-lang/infra

**Comment by RalfJung** [comment]
Rather suspiciously, my Travis cron job at https://travis-ci.com/github/RalfJung/miri-test-libstd/ also seems to have last run on 2021-06-09 (even though in the settings it claims it ran "9 hours ago"). That seems to be a bit too much for a coincidence -- did Travis cron jobs just stop working a few weeks ago?

**Comment by Mark-Simulacrum** [comment]
My guess is that https://github.com/rust-lang/rustup-components-history/pull/35 is the way to "fix" this, but I have not had a chance to take a look at it yet.

**Comment by sagudev** [comment]
> Rather suspiciously, my Travis cron job at https://travis-ci.com/github/RalfJung/miri-test-libstd/ also seems to have last run on 2021-06-09 (even though in the settings it claims it ran "9 hours ago"). That seems to be a bit too much for a coincidence -- did Travis cron jobs just stop working a few weeks ago?

Now that Travis changed their policy, they do not serve their CI for free to anyone any more. Most people just migrated to GitHub Actions. 
https://ropensci.org/blog/2020/11/19/moving-away-travis/#a-change-of-management
https://en.wikipedia.org/wiki/Travis_CI

**Comment by RalfJung** [comment]
> Now that Travis changed their policy, they do not serve their CI for free to anyone any more. 

Well, free CI worked until about a month ago, so I don't think this is directly related to that policy change from last November... and the UI definitely thinks that cronjob should still run.^^

But yeah, Travis has been going downhill rapidly. GHA actions are [massively overcomplicated and a supply chain risk](https://euroquis.nl//calamares/2021/06/17/actions), but at least they work. ;)

**Comment by sagudev** [comment]
> > Now that Travis changed their policy, they do not serve their CI for free to anyone any more.
> 
> Well, free CI worked until about a month ago, so I don't think this is directly related to that policy change from last November... and the UI definitely thinks that cronjob should still run.^^

You probably run out of credit.

**Comment by RalfJung** [comment]
Credit is monthly, is it not? It stopped on day 9 of the month. So, seems unlikely.

**Comment by sagudev** [comment]
You get one time 10000 free credit and that's it.

> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
> When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.
> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment.


from https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

**Comment by RalfJung** [comment]
Oh, and I guess they don't show how many credits one has, don't notify when credits run out, and don't show any error message for that case either? Great.

Well, about time to leave that sinking ship.^^

**Comment by sagudev** [comment]
You can check your credit status here: https://travis-ci.com/account/plan, but I also did not get notifications so lets boycott Travis.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rustup-components-history/pull/35 has been merged.

However, the job seems to run too early, before the new nightly is out: currently it should list the info for 2021-07-11, but instead it shows 2021-07-10. I was told that releasing can take an hour or more, so running at 2am UTC or so is probably better than running at 0:10 am UTC.

**Comment by sagudev** [comment]
Look at #11
