### ISSUE TITLE
No gh-actions update since 2021-09-12 due to 60 days of inactivity

### ISSUE THREAD

**Issue by MingweiSamuel** [rust-lang/rustup-components-history#42]
![image](https://user-images.githubusercontent.com/6778341/133670017-b8482b6a-6c01-4577-906c-f5168239b399.png)

https://github.com/rust-lang/rustup-components-history/actions/workflows/rust.yml

[PR:  Use GitHub Actions #35](https://github.com/rust-lang/rustup-components-history/pull/35)

Seems that it requires manual reactivation from the gh-actions gui by a repository admin:
* https://github.community/t/do-disabled-scheduled-workflows-re-activate-on-repository-activity/160658
* https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow

**Comment by pietroalbini** [comment]
Hmm, I see the workflow didn't execute since 5 days ago, but I don't see the warning you see.

**Comment by Mark-Simulacrum** [comment]
Oh forgot to comment -- I think I fixed it
