### ISSUE TITLE
Machine-readable version of "Last available"?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rustup-components-history#5]
For use-cases like running nightly Clippy or Miri on CI, it would be very useful to be able to determine the last version of rustc that had that component included. This site has all the necessary information for that, but it is not available in a machine-readable way. Do you think that would be a reasonable extension?

I could imagine either a JSON file (so a script could use `jq`), or maybe just one file per component containing the latest date (so plain `curl` is enough -- `jq` IIRC is not available on macOS with Travis).

**Comment by mexus** [comment]
Yeah it's quite a nice idea, and I'd say we can actually have both a single json that contains all the info and a set of files with dates.
Let's see what I can do about it :)

**Comment by mexus** [comment]
So what I came up with so far is generating a file tree like the following
![image](https://user-images.githubusercontent.com/3609357/59131187-5107ec80-897a-11e9-95c9-e6601bc457a4.png)
... with all the files containing the latest available date (like `2019-12-20`), and "no file" means "no info" for the meantime (the "meantime" is currently 29 days back in time).

So the data will be fetchable via a link like `http://rust-lang.github.io/rustup-components-history/last-available/x86_64-unknown-linux-gnu/rust-analysis`. @RalfJung did I miss anything?

**Comment by RalfJung** [comment]
That sounds pretty awesome! So I can just do `nightly-$(curl http://rust-lang.github.io/rustup-components-history/last-available/x86_64-unknown-linux-gnu/miri)` to figure out the last nightly with miri?

**Comment by mexus** [comment]
Yep! No json with all the info gathered in one place yet, but I hope I'll
come up with a viable solution in the next few days for that matter as well

**Comment by RalfJung** [comment]
Well this is already enough for my usecase, but there are probably others. :)

**Comment by mexus** [comment]
```
$ echo nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
nightly-2019-06-08
```
:tada:

**Comment by mexus** [comment]
I think I'll put on ice making a combined json file and close the issue for now :)

**Comment by RalfJung** [comment]
Awesome, thank you so much. :)

I'll play around with this later.
